''' 
SCRIPT TO POPULATE THE MELODYDB DATABASE
MAKES REQUESTS ON SPOTIFY API AND TRANSFERS DATA TO MELODYDB TABLES
'''

import sys
import requests
import json
import base64
import time
from html import unescape
import psycopg2


url = "https://accounts.spotify.com/api/token"
CLIENT_ID = "[redacted]"
CLIENT_SECRET = "[redacted]"
params = {
    "grant_type": "authorization_code",
    "code": "[redacted]",
    "redirect_uri": "http://127.0.0.1:5000/callback/", 
}

headers = {
    "Content-Type": "application/x-www-form-urlencoded",
    "Authorization" : "Basic " + base64.b64encode("{}:{}".format(CLIENT_ID, CLIENT_SECRET).encode('UTF-8')).decode('ascii')
}

def authorize():
    html = requests.request('post', url, headers=headers, params=params, data=None) 
    print(html.text)

#authorize()

#Standard list
artist_list = ["Drake",
                    "Ed Sheeran",
                    "Ariana Grande",
                    "Bad Bunny",
                    "The Weeknd",
                    "Post Malone",
                    "Justin Bieber",
                    "Eminem",
                    "Taylor Swift",
                    "J Balvin",
                    "BTS",
                    "Kanye West",
                    "Billie Eilish",
                    "Ozuna",
                    "Khalid",
                    "XXXTENTACION",
                    "Juice WRLD",
                    "Coldplay",
                    "Rihanna",
                    "Travis Scott",
                    "Imagine Dragons",
                    "Maroon 5",
                    "Dua Lipa",
                    "Shawn Mendes",
                    "David Guetta",
                    "Calvin Harris",
                    "Daddy Yankee",
                    "Sam Smith",
                    "Bruno Mars",
                    "The Chainsmokers",
                    "Queen",
                    "Kendrick Lamar",
                    "Beyoncé",
                    "Future",
                    "Chris Brown",
                    "One Direction",
                    "Sia",
                    "Nicki Minaj",
                    "Halsey",
                    "Lady Gaga",
                    "Selena Gomez",
                    "J. Cole",
                    "Anuel AA",
                    "The Beatles",
                    "Twenty One Pilots",
                    "Maluma",
                    "Kygo",
                    "Marshmello",
                    "Avicii",
                    "Linkin Park",
                    "Lil Uzi Vert",
                    "Katy Perry",
                    "Camila Cabello",
                    "Adele",
                    "Jason Derulo",
                    "Lana Del Rey",
                    "Farruko",
                    "Demi Lovato",
                    "Red Hot Chili Peppers",
                    "Nicky Jam",
                    "Shakira",
                    "Arctic Monkeys",
                    "Martin Garrix",
                    "Major Lazer",
                    "G-Eazy",
                    "Panic! At The Disco",
                    "OneRepublic",
                    "Miley Cyrus",
                    "Michael Jackson",
                    "Pitbull",
                    "Ellie Goulding",
                    "Cardi B",
                    "Charlie Puth",
                    "Harry Styles",
                    "Wiz Khalifa",
                    "Lil Wayne",
                    "KAROL G",
                    "Rauw Alejandro",
                    "Sebastian Yatra",
                    "Logic",
                    "Diplo",
                    "Fall Out Boy",
                    "Migos",
                    "Tyga",
                    "Young Thug",
                    "21 Savage",
                    "DaBaby",
                    "Alan Walker",
                    "John Mayer",
                    "Metallica",
                    "Macklemore",
                    "Sech",
                    "ZAYN",
                    "P!nk",
                    "DJ Snake",
                    "Lil Baby",
                    "Zedd",
                    "Lauv",
                    "Mac Miller",
                    "James Arthur",
                    "Little Mix",
                    "AC/DC",
                    "Lil Peep",
                    "Pop Smoke",
                    "Myke Towers",
                    "Robin Schulz",
                    "5 Seconds of Summer",
                    "Kodak Black",
                    "A$AP Rocky",
                    "A Boogie Wit da Hoodie",
                    "Justin Timberlake",
                    "Trippie Redd",
                    "NF",
                    "Romeo Santos",
                    "DJ Khaled",
                    "Metro Boomin",
                    "Clean Bandit",
                    "Zara Larsson",
                    "Green Day",
                    "Frank Ocean",
                    "Doja Cat",
                    "Bob Marley & The Wailers",
                    "Anne-Marie",
                    "Bebe Rexha",
                    "Tiësto",
                    "blackbear",
                    "Lewis Capaldi",
                    "Pink Floyd",
                    "Luis Fonsi",
                    "Luis Miguel",
                    "Flo Rida",
                    "Black Eyed Peas",
                    "Gunna",
                    "The Rolling Stones",
                    "Nirvana",
                    "JAY-Z",
                    "Jonas Blue",
                    "Michael Bublé",
                    "Elton John",
                    "YoungBoy Never Broke Again",
                    "Ty Dolla $ign",
                    "Russ",
                    "Fleetwood Mac",
                    "BLACKPINK",
                    "Tyler, The Creator",
                    "Bastille",
                    "Guns N\'\' Roses",
                    "Childish Gambino",
                    "Britney Spears",
                    "Big Sean",
                    "Machine Gun Kelly",
                    "SZA",
                    "Enrique Iglesias",
                    "Lil Nas X",
                    "Alessia Cara",
                    "Reik",
                    "Skrillex",
                    "Usher",
                    "Anitta",
                    "Lorde",
                    "David Bowie",
                    "French Montana",
                    "50 Cent",
                    "Kid Cudi",
                    "Hozier",
                    "Gorillaz",
                    "$uicideboy$",
                    "Olivia Rodrigo",
                    "Camilo",
                    "Becky G",
                    "Banda MS de Sergio Lizárraga",
                    "The Killers",
                    "Foo Fighters",
                    "Tory Lanez",
                    "Meek Mill",
                    "blink-182",
                    "Mariah Carey",
                    "Rae Sremmurd",
                    "Daft Punk",
                    "Meghan Trainor",
                    "John Legend",
                    "U2",
                    "6ix9ine",
                    "Gucci Mane",
                    "Led Zeppelin",
                    "Rita Ora",
                    "The 1975",
                    "Mumford & Sons",
                    "Luke Combs",
                    "Marília Mendonça",
                    "Manuel Turizo",
                    "Radiohead",
                    "Ava Max",
                    "Roddy Ricch",
                    "System Of A Down",
                    "Muse",
                    "Swae Lee",
                    "Hailee Steinfeld",
                    "Jack Johnson",
                    "Bazzi",
                    "The Neighbourhood",
                    "Elvis Presley",
                    "The Notorious B.I.G.",
                    "Snoop Dogg",
                    "Felix Jaehn",
                    "Frank Sinatra",
                    "Jess Glynne",
                    "Joji",
                    "Julia Michaels",
                    "Cheat Codes",
                    "Fifth Harmony",
                    "Paramore",
                    "Disclosure",
                    "Troye Sivan",
                    "Oasis",
                    "Florida Georgia Line",
                    "Polo G",
                    "Chance the Rapper",
                    "Jorge & Mateus",
                    "Don Omar",
                    "Kings of Leon",
                    "Bon Jovi",
                    "Dalex",
                    "Luke Bryan",
                    "Slipknot",
                    "Tove Lo",
                    "The Lumineers",
                    "Jason Mraz",
                    "Alicia Keys",
                    "The Script",
                    "Tame Impala",
                    "Jhay Cortez",
                    "6LACK",
                    "Paulo Londra",
                    "Glee Cast",
                    "Florence + The Machine",
                    "Lil Pump",
                    "Melanie Martinez",
                    "Natti Natasha",
                    "Five Finger Death Punch",
                    "Galantis",
                    "Nickelback",
                    "Justin Quiles",
                    "Alesso",
                    "Ne-Yo",
                    "Bruce Springsteen",
                    "Megan Thee Stallion",
                    "Christina Aguilera",
                    "Piso 21",
                    "Creedence Clearwater Revival",
                    "Kehlani",
                    "Bryson Tiller",
                    "Capital Bra",
                    "Madonna",
                    "2Pac",
                    "Whitney Houston",
                    "The Kid LAROI",
                    "Kane Brown",
                    "Christian Nodal",
                    "Rammstein",
                    "NAV",
                    "Labrinth",
                    "Niall Horan",
                    "My Chemical Romance",
                    "YG",
                    "Henrique & Juliano",
                    "Arcangel",
                    "ABBA",
                    "Playboi Carti",
                    "Alok",
                    "Zion & Lennox",
                    "Gusttavo Lima",
                    "James Bay",
                    "Thomas Rhett",
                    "Zé Neto & Cristiano",
                    "Vance Joy",
                    "Kevin Gates",
                    "Lenny Tavárez",
                    "Ryan Lewis",
                    "Flume",
                    "Jonas Brothers",
                    "Morat",
                    "Kelly Clarkson",
                    "Wisin",
                    "Aerosmith",
                    "Jennifer Lopez",
                    "Lil Skies",
                    "Stevie Wonder",
                    "Avril Lavigne",
                    "Miguel",
                    "Disturbed",
                    "Bring Me The Horizon",
                    "Amy Winehouse",
                    "Alejandro Fernández",
                    "Fetty Wap",
                    "Tones And I",
                    "Sean Paul",
                    "Backstreet Boys",
                    "Hans Zimmer",
                    "Maná",
                    "YNW Melly",
                    "Yandel",
                    "Dr. Dre",
                    "Wisin & Yandel",
                    "Jeremih",
                    "TWICE",
                    "Three Days Grace",
                    "Kesha",
                    "Steve Aoki",
                    "Why Don\'\'t We",
                    "Seeb",
                    "George Ezra",
                    "Jason Aldean",
                    "Morgan Wallen",
                    "Prince Royce",
                    "Phil Collins",
                    "Pearl Jam",
                    "Billy Joel",
                    "Trey Songz",
                    "Dan + Shay",
                    "Johnny Cash",
                    "Akon",
                    "Lil Mosey",
                    "Jessie J",
                    "Wesley Safadão",
                    "Eagles",
                    "benny blanco",
                    "Passenger",
                    "Lin-Manuel Miranda",
                    "Avenged Sevenfold",
                    "Lil Tecca",
                    "CNCO",
                    "The Offspring",
                    "Nio Garcia",
                    "Lukas Graham",
                    "Matheus & Kauan",
                    "Mark Ronson",
                    "The Strokes",
                    "2 Chainz",
                    "Lil Tjay",
                    "Céline Dion",
                    "Foster The People",
                    "Lizzo",
                    "Ricardo Arjona",
                    "Train",
                    "Ricky Martin",
                    "ScHoolboy Q",
                    "Bob Dylan",
                    "Rudimental",
                    "Pablo Alborán",
                    "Marc Anthony",
                    "James Blunt",
                    "Jul",
                    "Pentatonix",
                    "Macklemore & Ryan Lewis",
                    "Armin van Buuren",
                    "Aventura",
                    "H.E.R.",
                    "24kGoldn",
                    "Alejandro Sanz",
                    "Bon Iver",
                    "Sam Hunt",
                    "Lil Yachty",
                    "Liam Payne",
                    "Offset",
                    "Dire Straits",
                    "Quavo",
                    "Cartel De Santa",
                    "Zac Brown Band",
                    "Bryan Adams",
                    "Jhené Aiko",
                    "Nelly",
                    "BROCKHAMPTON",
                    "PARTYNEXTDOOR",
                    "Blake Shelton",
                    "Mike Posner",
                    "The Vamps",
                    "R3HAB",
                    "Don Toliver",
                    "Ski Mask The Slump God",
                    "Charli XCX",
                    "Duki",
                    "Ninho",
                    "Dean Lewis",
                    "Daniel Caesar",
                    "Bee Gees",
                    "Marvin Gaye",
                    "ILLENIUM",
                    "Boyce Avenue",
                    "Birdy",
                    "Skillet",
                    "The Police",
                    "Carlos Vives",
                    "Iron Maiden",
                    "Tim McGraw",
                    "The Black Keys",
                    "Rise Against",
                    "John Williams",
                    "A$AP Ferg",
                    "T.I.",
                    "Lil Durk",
                    "Juanes",
                    "Danny Ocean",
                    "Iggy Azalea",
                    "Maren Morris",
                    "Carly Rae Jepsen",
                    "The Doors",
                    "Bradley Cooper",
                    "alt-J",
                    "Cage The Elephant",
                    "Anderson .Paak",
                    "Alec Benjamin",
                    "LANY",
                    "Weezer",
                    "Sigala",
                    "Hillsong Worship",
                    "Journey",
                    "La Arrolladora Banda El Limón De Rene Camacho",
                    "Jeremy Zucker",
                    "Calibre 50",
                    "SAINt JHN",
                    "Nick Jonas",
                    "Rex Orange County",
                    "Kenny Chesney",
                    "Glass Animals",
                    "Soda Stereo",
                    "Mau y Ricky",
                    "MAGIC!",
                    "The xx",
                    "Noah Cyrus",
                    "RAF Camora",
                    "Lunay",
                    "Sam Feldt",
                    "JP Cooper",
                    "Madison Beer",
                    "Jack Harlow",
                    "The Cure",
                    "Norah Jones",
                    "Juan Gabriel",
                    "iann dior",
                    "ROSALÍA",
                    "Jon Bellion",
                    "Kid Ink",
                    "Destiny\'\'s Child",
                    "EXO",
                    "Arijit Singh",
                    "Rich The Kid",
                    "Jesse & Joy",
                    "Dimitri Vegas & Like Mike",
                    "Mabel",
                    "Simon & Garfunkel",
                    "Paul McCartney",
                    "X Ambassadors",
                    "Chris Stapleton",
                    "Depeche Mode",
                    "Normani",
                    "Lost Frequencies",
                    "Grey",
                    "Aminé",
                    "Outkast",
                    "Breaking Benjamin",
                    "Matoma",
                    "Korn",
                    "Eric Clapton",
                    "Hillsong UNITED",
                    "Ufo361",
                    "PNL",
                    "Jax Jones",
                    "The Game",
                    "The Beach Boys",
                    "NLE Choppa",
                    "Volbeat",
                    "Papa Roach",
                    "AJR",
                    "Maiara & Maraisa",
                    "Jimi Hendrix",
                    "Os Barões Da Pisadinha",
                    "DNCE",
                    "Bonez MC",
                    "B.o.B",
                    "Eric Church",
                    "Conan Gray",
                    "Christina Perri",
                    "KYLE",
                    "The Fray",
                    "Years & Years",
                    "Juan Magán",
                    "Imanbek",
                    "Becky Hill",
                    "Sabrina Carpenter",
                    "Summer Walker",
                    "Calum Scott",
                    "Ludovico Einaudi",
                    "George Michael",
                    "MARINA",
                    "Shinedown",
                    "All Time Low",
                    "Van Morrison",
                    "Robbie Williams",
                    "R.E.M.",
                    "Stormzy",
                    "Earth, Wind & Fire",
                    "Rick Ross",
                    "Of Monsters and Men",
                    "Axwell /\ Ingrosso",
                    "Lynyrd Skynyrd",
                    "Keith Urban",
                    "A Day To Remember",
                    "TOTO",
                    "Rels B",
                    "T-Pain",
                    "Andy Grammer",
                    "Vicente Fernández",
                    "Rage Against The Machine",
                    "The Smiths",
                    "KHEA",
                    "PnB Rock",
                    "Hollywood Undead",
                    "Daryl Hall & John Oates",
                    "Dermot Kennedy",
                    "The Cranberries",
                    "The White Stripes",
                    "Brytiago",
                    "Scorpions",
                    "ODESZA",
                    "Aya Nakamura",
                    "bbno$",
                    "Milky Chance",
                    "GIMS",
                    "Black Sabbath",
                    "Bizarrap",
                    "Mustard",
                    "Rag\'\'n\'\'Bone Man",
                    "Pedro Capó",
                    "Prince",
                    "El Alfa",
                    "Van Halen",
                    "Los Ángeles Azules",
                    "Shaggy",
                    "Tate McRae",
                    "Enya",
                    "gnash",
                    "WALK THE MOON",
                    "Aretha Franklin",
                    "Hardwell",
                    "Carrie Underwood",
                    "Kodaline",
                    "Don Diablo",
                    "MEDUZA",
                    "Sublime",
                    "Rod Stewart",
                    "Sabaton",
                    "Samra",
                    "Måneskin",
                    "George Strait",
                    "Damso",
                    "Nacho",
                    "Evanescence",
                    "Mac DeMarco",
                    "Sum 41",
                    "De La Ghetto",
                    "Kali Uchis",
                    "Sfera Ebbasta",
                    "Two Door Cinema Club",
                    "MGMT",
                    "Nelly Furtado",
                    "C. Tangana",
                    "Colbie Caillat",
                    "Desiigner",
                    "R. Kelly",
                    "Ella Mai",
                    "Ozzy Osbourne",
                    "Noriel",
                    "Cali Y El Dandee",
                    "Rascal Flatts",
                    "3 Doors Down",
                    "Melendi",
                    "Gotye",
                    "Red Velvet",
                    "Louis Tomlinson",
                    "Astrid S",
                    "Arizona Zervas",
                    "Marilyn Manson",
                    "MC Kevinho",
                    "RAYE",
                    "Clairo",
                    "Luciano",
                    "Vampire Weekend",
                    "Goodboys",
                    "OMI",
                    "Jorja Smith",
                    "Limp Bizkit",
                    "MØ",
                    "Joan Sebastian",
                    "Mike WiLL Made-It",
                    "Sleeping At Last",
                    "Jaden",
                    "M83",
                    "The Kooks",
                    "Pharrell Williams",
                    "Thirty Seconds To Mars",
                    "Portugal. The Man",
                    "The Clash",
                    "Ms. Lauryn Hill",
                    "Stefflon Don",
                    "Lofi Fruits Music",
                    "The Smashing Pumpkins",
                    "Jessie Reyez",
                    "El Fantasma",
                    "Loud Luxury",
                    "Annie Lennox",
                    "Carlos Rivera",
                    "Kontra K",
                    "Luan Santana",
                    "Michael Silverman",
                    "Olly Murs",
                    "Topic",
                    "Queens of the Stone Age",
                    "Joey Bada$$",
                    "Owl City",
                    "Gerardo Ortiz",
                    "Westlife",
                    "Dierks Bentley",
                    "DMX",
                    "Snow Patrol",
                    "Dave",
                    "Ha*Ash",
                    "Joyner Lucas",
                    "Kelly Rowland",
                    "Keane",
                    "Afrojack",
                    "Incubus",
                    "Gryffin",
                    "Apache 207",
                    "Powfu",
                    "Tee Grizzley",
                    "Lil Dicky",
                    "Stray Kids",
                    "Yo Gotti",
                    "Los Tigres Del Norte",
                    "Ali Gatie",
                    "Gigi D\'\'Agostino",
                    "Aloe Blacc",
                    "Nekfeu",
                    "Tom Odell",
                    "Ciara",
                    "Cosculluela",
                    "Santana",
                    "Trevor Daniel",
                    "KISS",
                    "Rod Wave",
                    "Quinn XCII",
                    "TKKG",
                    "Elevation Worship",
                    "Frédéric Chopin",
                    "Wale",
                    "MAX",
                    "Sara Bareilles",
                    "Conor Maynard",
                    "Jay Wheeler",
                    "Kacey Musgraves",
                    "Swedish House Mafia",
                    "Zoé",
                    "Thalia",
                    "Ben Howard",
                    "Old Dominion",
                    "SEVENTEEN",
                    "Bryant Myers",
                    "Willy William",
                    "Lady A",
                    "Booba",
                    "CHVRCHES",
                    "Martin Jensen",
                    "Moneybagg Yo",
                    "Blueface",
                    "Nas",
                    "Wham!",
                    "Mötley Crüe",
                    "ANAVITÓRIA",
                    "Gente De Zona",
                    "La Oreja de Van Gogh",
                    "Sufjan Stevens",
                    "Natanael Cano",
                    "Bethel Music",
                    "Daya",
                    "Danna Paola",
                    "Leona Lewis",
                    "Casper Magico",
                    "fun.",
                    "TINI",
                    "The Jackson 5",
                    "Chief Keef",
                    "Gwen Stefani",
                    "Lee Brice",
                    "Jack Ü",
                    "Sido",
                    "Felipe Araújo",
                    "Fergie",
                    "Bruno & Marrone",
                    "Sting",
                    "Lord Huron",
                    "Ice Cube",
                    "Neil Young",
                    "John Lennon",
                    "Arcade Fire",
                    "Kevin Roldan",
                    "Kollegah",
                    "Taio Cruz",
                    "Internet Money",
                    "Charlie Brown Jr.",
                    "Alan Jackson",
                    "Martin Solveig",
                    "Denzel Curry",
                    "MKTO",
                    "Tainy",
                    "AJ Tracey",
                    "Banda El Recodo",
                    "The National",
                    "Darell",
                    "Yellow Claw",
                    "Nat King Cole",
                    "Chayanne",
                    "Guaynaa",
                    "Sean Kingston",
                    "Roxette",
                    "Plan B",
                    "Mon Laferte",
                    "Paul Simon",
                    "John Newman",
                    "Saweetie",
                    "Yung Gravy",
                    "Granular",
                    "Nipsey Hussle",
                    "Stromae",
                    "Alex Rose",
                    "José José",
                    "Chelsea Cutler",
                    "Beret",
                    "DJ Luian",
                    "Shania Twain",
                    "Electric Light Orchestra",
                    "DENNIS",
                    "Calle 13",
                    "Lily Allen",
                    "Marco Antonio Solís",
                    "Mambo Kingz",
                    "Bullet For My Valentine",
                    "Dolly Parton",
                    "Brad Paisley",
                    "deadmau5",
                    "Simple Plan",
                    "Yusuf / Cat Stevens",
                    "Niska",
                    "The Pussycat Dolls",
                    "Lionel Richie",
                    "League of Legends",
                    "The Goo Goo Dolls",
                    "Jay Chou",
                    "Mike Perry",
                    "David Bisbal",
                    "*NSYNC",
                    "Sade",
                    "Chencho Corleone",
                    "Dilsinho",
                    "will.i.am",
                    "Nina Simone",
                    "Kylie Minogue",
                    "Mr. Probz",
                    "Aitana",
                    "Ferrugem",
                    "James TW",
                    "Bea Miller",
                    "The Who",
                    "Dennis Lloyd",
                    "Willie Nelson",
                    "Summer Cem",
                    "Lalo Ebratt",
                    "Angus & Julia Stone",
                    "Gavin James",
                    "Bing Crosby",
                    "Natalia Lafourcade",
                    "Tech N9ne",
                    "Oh Wonder",
                    "Miranda Lambert",
                    "Brett Young",
                    "Tracy Chapman",
                    "Kiiara",
                    "Jack & Jack",
                    "Bill Withers",
                    "Surfaces",
                    "Dido",
                    "Jeezy",
                    "Audioslave",
                    "Grupo Firme",
                    "Jasmine Thompson",
                    "Ruth B.",
                    "Greeicy",
                    "Will Smith",
                    "Tom Walker",
                    "Tears For Fears",
                    "Cyndi Lauper",
                    "Olivia O\'\'Brien",
                    "Ella Fitzgerald",
                    "Wolfgang Amadeus Mozart",
                    "Jon Pardi",
                    "Jowell & Randy",
                    "Tina Turner",
                    "Lenny Kravitz",
                    "YUNGBLUD",
                    "Genesis",
                    "Sin Bandera",
                    "Blur",
                    "Lil Xan",
                    "KSI",
                    "Brantley Gilbert",
                    "Lil Kleine",
                    "ZZ Top",
                    "Ramin Djawadi",
                    "Louis Armstrong",
                    "Snakehips",
                    "Natiruts",
                    "Sofía Reyes",
                    "Cigarettes After Sex",
                    "Selena",
                    "Oliver Heldens",
                    "Skepta",
                    "NEFFEX",
                    "Rich Brian",
                    "girl in red",
                    "Ezhel",
                    "LUDMILLA",
                    "Dean Martin",
                    "The Head And The Heart",
                    "Lupe Fiasco",
                    "Tinie Tempah",
                    "Alina Baraz",
                    "Capo Plaza",
                    "TLC",
                    "Lil Jon",
                    "Toby Keith",
                    "Lauren Daigle",
                    "Tori Kelly",
                    "Maggie Lindemann",
                    "ZHU",
                    "Juicy J",
                    "Pabllo Vittar",
                    "Dynoro",
                    "Ghostemane",
                    "Alice In Chains",
                    "Chris Young",
                    "Alvaro Soler",
                    "Beck",
                    "Gustavo Cerati",
                    "Salaam Remi",
                    "Bruno Martini",
                    "Timbaland",
                    "Tungevaag",
                    "Feid",
                    "Spice Girls",
                    "Cher",
                    "Kina",
                    "Mary J. Blige",
                    "Seether",
                    "Luísa Sonza",
                    "Kris Kross Amsterdam",
                    "Max Richter",
                    "Andrea Bocelli",
                    "Leon Bridges",
                    "Brent Faiyaz",
                    "Showtek",
                    "Cash Cash",
                    "Lykke Li",
                    "Timmy Trumpet",
                    "Intocable",
                    "The All-American Rejects",
                    "BØRNS",
                    "a-ha",
                    "IU",
                    "Vince Staples",
                    "AWOLNATION",
                    "Deftones",
                    "Camila",
                    "Melim",
                    "Otis Redding",
                    "A R I Z O N A",
                    "Jacquees",
                    "Petit Biscuit",
                    "Emeli Sandé",
                    "Foals",
                    "Simone & Simaria",
                    "Jake Owen",
                    "Wu-Tang Clan",
                    "Dadju",
                    "Craig David",
                    "Frenna",
                    "Gustavo Mioto",
                    "Supertramp",
                    "A Tribe Called Quest",
                    "Counting Crows",
                    "Pineapple StormTv",
                    "Grouplove",
                    "Cro",
                    "Baby Lullaby Academy",
                    "Pixies",
                    "Beastie Boys",
                    "Talking Heads",
                    "KALEO",
                    "Regard",
                    "Gemitaiz",
                    "Ludacris",
                    "Dustin Lynch",
                    "The Score",
                    "Foreigner",
                    "Missy Elliott",
                    "Sam Cooke",
                    "Death Cab for Cutie",
                    "Dave Matthews Band",
                    "Río Roma",
                    "The Temptations",
                    "Banda Los Recoditos",
                    "Alanis Morissette",
                    "Kungs",
                    "Stone Sour",
                    "NCT 127",
                    "Grateful Dead",
                    "Two Feet",
                    "La Adictiva Banda San José de Mesillas",
                    "beabadoobee",
                    "Icona Pop",
                    "Empire of the Sun",
                    "Megadeth",
                    "Los Temerarios",
                    "Moby",
                    "MadeinTYO",
                    "Famous Dex",
                    "Tom Petty and the Heartbreakers",
                    "Ella Eyre",
                    "ONE OK ROCK",
                    "Eurythmics",
                    "LMFAO",
                    "RIN",
                    "Gym Class Heroes",
                    "M.I.A.",
                    "Los Enanitos Verdes",
                    "Lindsey Stirling",
                    "SCH",
                    "Disciples",
                    "Gloria Trevi",
                    "KSHMR",
                    "A Great Big World",
                    "Phoenix",
                    "KC Rebell",
                    "Roy Woods",
                    "EDEN",
                    "Juan Luis Guerra 4.40",
                    "Ultimo",
                    "Fat Joe",
                    "Darius Rucker",
                    "Salmo",
                    "Vintage Culture",
                    "Bunbury",
                    "Iron & Wine",
                    "Jamiroquai",
                    "Digital Farm Animals",
                    "MC Kevin o Chris",
                    "BIGBANG",
                    "UB40",
                    "Wallows",
                    "Ricardo Montaner",
                    "Canserbero",
                    "No Doubt",
                    "Thiaguinho",
                    "Kaskade",
                    "Duke Dumont",
                    "Eladio Carrion",
                    "Alle Farben",
                    "Brooks & Dunn",
                    "The Kinks",
                    "Falling In Reverse",
                    "American Authors",
                    "AURORA",
                    "Ben&Ben",
                    "Leonard Cohen",
                    "Micro TDH",
                    "Pantera",
                    "Chicago",
                    "Matchbox Twenty",
                    "Smokepurpp",
                    "Kelsea Ballerini",
                    "Burna Boy",
                    "Jawsh 685",
                    "Jay Rock",
                    "Young the Giant",
                    "GoldLink",
                    "Slim Jxmmi",
                    "Deep Purple",
                    "Chet Faker",
                    "Ruel",
                    "Brett Eldredge",
                    "Mc Livinho"]

#List for queries
artist_list_two = ["Drake",
                    "Ed+Sheeran",
                    "Ariana+Grande",
                    "Bad+Bunny",
                    "The+Weeknd",
                    "Post+Malone",
                    "Justin+Bieber",
                    "Eminem",
                    "Taylor+Swift",
                    "J+Balvin",
                    "BTS",
                    "Kanye+West",
                    "Billie+Eilish",
                    "Ozuna",
                    "Khalid",
                    "XXXTENTACION",
                    "Juice+WRLD",
                    "Coldplay",
                    "Rihanna",
                    "Travis+Scott",
                    "Imagine+Dragons",
                    "Maroon+5",
                    "Dua+Lipa",
                    "Shawn+Mendes",
                    "David+Guetta",
                    "Calvin+Harris",
                    "Daddy+Yankee",
                    "Sam+Smith",
                    "Bruno+Mars",
                    "The+Chainsmokers",
                    "Queen",
                    "Kendrick+Lamar",
                    "Beyoncé",
                    "Future",
                    "Chris+Brown",
                    "One+Direction",
                    "Sia",
                    "Nicki+Minaj",
                    "Halsey",
                    "Lady+Gaga",
                    "Selena+Gomez",
                    "J.+Cole",
                    "Anuel+AA",
                    "The+Beatles",
                    "Twenty+One+Pilots",
                    "Maluma",
                    "Kygo",
                    "Marshmello",
                    "Avicii",
                    "Linkin+Park",
                    "Lil+Uzi+Vert",
                    "Katy+Perry",
                    "Camila+Cabello",
                    "Adele",
                    "Jason+Derulo",
                    "Lana+Del+Rey",
                    "Farruko",
                    "Demi+Lovato",
                    "Red+Hot+Chili+Peppers",
                    "Nicky+Jam",
                    "Shakira",
                    "Arctic+Monkeys",
                    "Martin+Garrix",
                    "Major+Lazer",
                    "G-Eazy",
                    "Panic!+At+The+Disco",
                    "OneRepublic",
                    "Miley+Cyrus",
                    "Michael+Jackson",
                    "Pitbull",
                    "Ellie+Goulding",
                    "Cardi+B",
                    "Charlie+Puth",
                    "Harry+Styles",
                    "Wiz+Khalifa",
                    "Lil+Wayne",
                    "KAROL+G",
                    "Rauw+Alejandro",
                    "Sebastian+Yatra",
                    "Logic",
                    "Diplo",
                    "Fall+Out+Boy",
                    "Migos",
                    "Tyga",
                    "Young+Thug",
                    "21+Savage",
                    "DaBaby",
                    "Alan+Walker",
                    "John+Mayer",
                    "Metallica",
                    "Macklemore",
                    "Sech",
                    "ZAYN",
                    "P!nk",
                    "DJ+Snake",
                    "Lil+Baby",
                    "Zedd",
                    "Lauv",
                    "Mac+Miller",
                    "James+Arthur",
                    "Little+Mix",
                    "AC/DC",
                    "Lil+Peep",
                    "Pop+Smoke",
                    "Myke+Towers",
                    "Robin+Schulz",
                    "5+Seconds+of+Summer",
                    "Kodak+Black",
                    "A$AP+Rocky",
                    "A+Boogie+Wit+da+Hoodie",
                    "Justin+Timberlake",
                    "Trippie+Redd",
                    "NF",
                    "Romeo+Santos",
                    "DJ+Khaled",
                    "Metro+Boomin",
                    "Clean+Bandit",
                    "Zara+Larsson",
                    "Green+Day",
                    "Frank+Ocean",
                    "Doja+Cat",
                    "Bob+Marley+&+The+Wailers",
                    "Anne-Marie",
                    "Bebe+Rexha",
                    "Tiësto",
                    "blackbear",
                    "Lewis+Capaldi",
                    "Pink+Floyd",
                    "Luis+Fonsi",
                    "Luis+Miguel",
                    "Flo+Rida",
                    "Black+Eyed+Peas",
                    "Gunna",
                    "The+Rolling+Stones",
                    "Nirvana",
                    "JAY-Z",
                    "Jonas+Blue",
                    "Michael+Bublé",
                    "Elton+John",
                    "YoungBoy+Never+Broke+Again",
                    "Ty+Dolla+$ign",
                    "Russ",
                    "Fleetwood+Mac",
                    "BLACKPINK",
                    "Tyler,+The+Creator",
                    "Bastille",
                    "Guns+N\'\'+Roses",
                    "Childish+Gambino",
                    "Britney+Spears",
                    "Big+Sean",
                    "Machine+Gun+Kelly",
                    "SZA",
                    "Enrique+Iglesias",
                    "Lil+Nas+X",
                    "Alessia+Cara",
                    "Reik",
                    "Skrillex",
                    "Usher",
                    "Anitta",
                    "Lorde",
                    "David+Bowie",
                    "French+Montana",
                    "50+Cent",
                    "Kid+Cudi",
                    "Hozier",
                    "Gorillaz",
                    "$uicideboy$",
                    "Olivia+Rodrigo",
                    "Camilo",
                    "Becky+G",
                    "Banda+MS+de+Sergio+Lizárraga",
                    "The+Killers",
                    "Foo+Fighters",
                    "Tory+Lanez",
                    "Meek+Mill",
                    "blink-182",
                    "Mariah+Carey",
                    "Rae+Sremmurd",
                    "Daft+Punk",
                    "Meghan+Trainor",
                    "John+Legend",
                    "U2",
                    "6ix9ine",
                    "Gucci+Mane",
                    "Led+Zeppelin",
                    "Rita+Ora",
                    "The+1975",
                    "Mumford+&+Sons",
                    "Luke+Combs",
                    "Marília+Mendonça",
                    "Manuel+Turizo",
                    "Radiohead",
                    "Ava+Max",
                    "Roddy+Ricch",
                    "System+Of+A+Down",
                    "Muse",
                    "Swae+Lee",
                    "Hailee+Steinfeld",
                    "Jack+Johnson",
                    "Bazzi",
                    "The+Neighbourhood",
                    "Elvis+Presley",
                    "The+Notorious+B.I.G.",
                    "Snoop+Dogg",
                    "Felix+Jaehn",
                    "Frank+Sinatra",
                    "Jess+Glynne",
                    "Joji",
                    "Julia+Michaels",
                    "Cheat+Codes",
                    "Fifth+Harmony",
                    "Paramore",
                    "Disclosure",
                    "Troye+Sivan",
                    "Oasis",
                    "Florida+Georgia+Line",
                    "Polo+G",
                    "Chance+the+Rapper",
                    "Jorge+&+Mateus",
                    "Don+Omar",
                    "Kings+of+Leon",
                    "Bon+Jovi",
                    "Dalex",
                    "Luke+Bryan",
                    "Slipknot",
                    "Tove+Lo",
                    "The+Lumineers",
                    "Jason+Mraz",
                    "Alicia+Keys",
                    "The+Script",
                    "Tame+Impala",
                    "Jhay+Cortez",
                    "6LACK",
                    "Paulo+Londra",
                    "Glee+Cast",
                    "Florence+++The+Machine",
                    "Lil+Pump",
                    "Melanie+Martinez",
                    "Natti+Natasha",
                    "Five+Finger+Death+Punch",
                    "Galantis",
                    "Nickelback",
                    "Justin+Quiles",
                    "Alesso",
                    "Ne-Yo",
                    "Bruce+Springsteen",
                    "Megan+Thee+Stallion",
                    "Christina+Aguilera",
                    "Piso+21",
                    "Creedence+Clearwater+Revival",
                    "Kehlani",
                    "Bryson+Tiller",
                    "Capital+Bra",
                    "Madonna",
                    "2Pac",
                    "Whitney+Houston",
                    "The+Kid+LAROI",
                    "Kane+Brown",
                    "Christian+Nodal",
                    "Rammstein",
                    "NAV",
                    "Labrinth",
                    "Niall+Horan",
                    "My+Chemical+Romance",
                    "YG",
                    "Henrique+&+Juliano",
                    "Arcangel",
                    "ABBA",
                    "Playboi+Carti",
                    "Alok",
                    "Zion+&+Lennox",
                    "Gusttavo+Lima",
                    "James+Bay",
                    "Thomas+Rhett",
                    "Zé+Neto+&+Cristiano",
                    "Vance+Joy",
                    "Kevin+Gates",
                    "Lenny+Tavárez",
                    "Ryan+Lewis",
                    "Flume",
                    "Jonas+Brothers",
                    "Morat",
                    "Kelly+Clarkson",
                    "Wisin",
                    "Aerosmith",
                    "Jennifer+Lopez",
                    "Lil+Skies",
                    "Stevie+Wonder",
                    "Avril+Lavigne",
                    "Miguel",
                    "Disturbed",
                    "Bring+Me+The+Horizon",
                    "Amy+Winehouse",
                    "Alejandro+Fernández",
                    "Fetty+Wap",
                    "Tones+And+I",
                    "Sean+Paul",
                    "Backstreet+Boys",
                    "Hans+Zimmer",
                    "Maná",
                    "YNW+Melly",
                    "Yandel",
                    "Dr.+Dre",
                    "Wisin+&+Yandel",
                    "Jeremih",
                    "TWICE",
                    "Three+Days+Grace",
                    "Kesha",
                    "Steve+Aoki",
                    "Why+Don\'\'t+We",
                    "Seeb",
                    "George+Ezra",
                    "Jason+Aldean",
                    "Morgan+Wallen",
                    "Prince+Royce",
                    "Phil+Collins",
                    "Pearl+Jam",
                    "Billy+Joel",
                    "Trey+Songz",
                    "Dan+++Shay",
                    "Johnny+Cash",
                    "Akon",
                    "Lil+Mosey",
                    "Jessie+J",
                    "Wesley+Safadão",
                    "Eagles",
                    "benny+blanco",
                    "Passenger",
                    "Lin-Manuel+Miranda",
                    "Avenged+Sevenfold",
                    "Lil+Tecca",
                    "CNCO",
                    "The+Offspring",
                    "Nio+Garcia",
                    "Lukas+Graham",
                    "Matheus+&+Kauan",
                    "Mark+Ronson",
                    "The+Strokes",
                    "2+Chainz",
                    "Lil+Tjay",
                    "Céline+Dion",
                    "Foster+The+People",
                    "Lizzo",
                    "Ricardo+Arjona",
                    "Train",
                    "Ricky+Martin",
                    "ScHoolboy+Q",
                    "Bob+Dylan",
                    "Rudimental",
                    "Pablo+Alborán",
                    "Marc+Anthony",
                    "James+Blunt",
                    "Jul",
                    "Pentatonix",
                    "Macklemore+&+Ryan+Lewis",
                    "Armin+van+Buuren",
                    "Aventura",
                    "H.E.R.",
                    "24kGoldn",
                    "Alejandro+Sanz",
                    "Bon+Iver",
                    "Sam+Hunt",
                    "Lil+Yachty",
                    "Liam+Payne",
                    "Offset",
                    "Dire+Straits",
                    "Quavo",
                    "Cartel+De+Santa",
                    "Zac+Brown+Band",
                    "Bryan+Adams",
                    "Jhené+Aiko",
                    "Nelly",
                    "BROCKHAMPTON",
                    "PARTYNEXTDOOR",
                    "Blake+Shelton",
                    "Mike+Posner",
                    "The+Vamps",
                    "R3HAB",
                    "Don+Toliver",
                    "Ski+Mask+The+Slump+God",
                    "Charli+XCX",
                    "Duki",
                    "Ninho",
                    "Dean+Lewis",
                    "Daniel+Caesar",
                    "Bee+Gees",
                    "Marvin+Gaye",
                    "ILLENIUM",
                    "Boyce+Avenue",
                    "Birdy",
                    "Skillet",
                    "The+Police",
                    "Carlos+Vives",
                    "Iron+Maiden",
                    "Tim+McGraw",
                    "The+Black+Keys",
                    "Rise+Against",
                    "John+Williams",
                    "A$AP+Ferg",
                    "T.I.",
                    "Lil+Durk",
                    "Juanes",
                    "Danny+Ocean",
                    "Iggy+Azalea",
                    "Maren+Morris",
                    "Carly+Rae+Jepsen",
                    "The+Doors",
                    "Bradley+Cooper",
                    "alt-J",
                    "Cage+The+Elephant",
                    "Anderson+.Paak",
                    "Alec+Benjamin",
                    "LANY",
                    "Weezer",
                    "Sigala",
                    "Hillsong+Worship",
                    "Journey",
                    "La+Arrolladora+Banda+El+Limón+De+Rene+Camacho",
                    "Jeremy+Zucker",
                    "Calibre+50",
                    "SAINt+JHN",
                    "Nick+Jonas",
                    "Rex+Orange+County",
                    "Kenny+Chesney",
                    "Glass+Animals",
                    "Soda+Stereo",
                    "Mau+y+Ricky",
                    "MAGIC!",
                    "The+xx",
                    "Noah+Cyrus",
                    "RAF+Camora",
                    "Lunay",
                    "Sam+Feldt",
                    "JP+Cooper",
                    "Madison+Beer",
                    "Jack+Harlow",
                    "The+Cure",
                    "Norah+Jones",
                    "Juan+Gabriel",
                    "iann+dior",
                    "ROSALÍA",
                    "Jon+Bellion",
                    "Kid+Ink",
                    "Destiny\'\'s+Child",
                    "EXO",
                    "Arijit+Singh",
                    "Rich+The+Kid",
                    "Jesse+&+Joy",
                    "Dimitri+Vegas+&+Like+Mike",
                    "Mabel",
                    "Simon+&+Garfunkel",
                    "Paul+McCartney",
                    "X+Ambassadors",
                    "Chris+Stapleton",
                    "Depeche+Mode",
                    "Normani",
                    "Lost+Frequencies",
                    "Grey",
                    "Aminé",
                    "Outkast",
                    "Breaking+Benjamin",
                    "Matoma",
                    "Korn",
                    "Eric+Clapton",
                    "Hillsong+UNITED",
                    "Ufo361",
                    "PNL",
                    "Jax+Jones",
                    "The+Game",
                    "The+Beach+Boys",
                    "NLE+Choppa",
                    "Volbeat",
                    "Papa+Roach",
                    "AJR",
                    "Maiara+&+Maraisa",
                    "Jimi+Hendrix",
                    "Os+Barões+Da+Pisadinha",
                    "DNCE",
                    "Bonez+MC",
                    "B.o.B",
                    "Eric+Church",
                    "Conan+Gray",
                    "Christina+Perri",
                    "KYLE",
                    "The+Fray",
                    "Years+&+Years",
                    "Juan+Magán",
                    "Imanbek",
                    "Becky+Hill",
                    "Sabrina+Carpenter",
                    "Summer+Walker",
                    "Calum+Scott",
                    "Ludovico+Einaudi",
                    "George+Michael",
                    "MARINA",
                    "Shinedown",
                    "All+Time+Low",
                    "Van+Morrison",
                    "Robbie+Williams",
                    "R.E.M.",
                    "Stormzy",
                    "Earth,+Wind+&+Fire",
                    "Rick+Ross",
                    "Of+Monsters+and+Men",
                    "Axwell+/\+Ingrosso",
                    "Lynyrd+Skynyrd",
                    "Keith+Urban",
                    "A+Day+To+Remember",
                    "TOTO",
                    "Rels+B",
                    "T-Pain",
                    "Andy+Grammer",
                    "Vicente+Fernández",
                    "Rage+Against+The+Machine",
                    "The+Smiths",
                    "KHEA",
                    "PnB+Rock",
                    "Hollywood+Undead",
                    "Daryl+Hall+&+John+Oates",
                    "Dermot+Kennedy",
                    "The+Cranberries",
                    "The+White+Stripes",
                    "Brytiago",
                    "Scorpions",
                    "ODESZA",
                    "Aya+Nakamura",
                    "bbno$",
                    "Milky+Chance",
                    "GIMS",
                    "Black+Sabbath",
                    "Bizarrap",
                    "Mustard",
                    "Rag\'\'n\'\'Bone+Man",
                    "Pedro+Capó",
                    "Prince",
                    "El+Alfa",
                    "Van+Halen",
                    "Los+Ángeles+Azules",
                    "Shaggy",
                    "Tate+McRae",
                    "Enya",
                    "gnash",
                    "WALK+THE+MOON",
                    "Aretha+Franklin",
                    "Hardwell",
                    "Carrie+Underwood",
                    "Kodaline",
                    "Don+Diablo",
                    "MEDUZA",
                    "Sublime",
                    "Rod+Stewart",
                    "Sabaton",
                    "Samra",
                    "Måneskin",
                    "George+Strait",
                    "Damso",
                    "Nacho",
                    "Evanescence",
                    "Mac+DeMarco",
                    "Sum+41",
                    "De+La+Ghetto",
                    "Kali+Uchis",
                    "Sfera+Ebbasta",
                    "Two+Door+Cinema+Club",
                    "MGMT",
                    "Nelly+Furtado",
                    "C.+Tangana",
                    "Colbie+Caillat",
                    "Desiigner",
                    "R.+Kelly",
                    "Ella+Mai",
                    "Ozzy+Osbourne",
                    "Noriel",
                    "Cali+Y+El+Dandee",
                    "Rascal+Flatts",
                    "3+Doors+Down",
                    "Melendi",
                    "Gotye",
                    "Red+Velvet",
                    "Louis+Tomlinson",
                    "Astrid+S",
                    "Arizona+Zervas",
                    "Marilyn+Manson",
                    "MC+Kevinho",
                    "RAYE",
                    "Clairo",
                    "Luciano",
                    "Vampire+Weekend",
                    "Goodboys",
                    "OMI",
                    "Jorja+Smith",
                    "Limp+Bizkit",
                    "MØ",
                    "Joan+Sebastian",
                    "Mike+WiLL+Made-It",
                    "Sleeping+At+Last",
                    "Jaden",
                    "M83",
                    "The+Kooks",
                    "Pharrell+Williams",
                    "Thirty+Seconds+To+Mars",
                    "Portugal.+The+Man",
                    "The+Clash",
                    "Ms.+Lauryn+Hill",
                    "Stefflon+Don",
                    "Lofi+Fruits+Music",
                    "The+Smashing+Pumpkins",
                    "Jessie+Reyez",
                    "El+Fantasma",
                    "Loud+Luxury",
                    "Annie+Lennox",
                    "Carlos+Rivera",
                    "Kontra+K",
                    "Luan+Santana",
                    "Michael+Silverman",
                    "Olly+Murs",
                    "Topic",
                    "Queens+of+the+Stone+Age",
                    "Joey+Bada$$",
                    "Owl+City",
                    "Gerardo+Ortiz",
                    "Westlife",
                    "Dierks+Bentley",
                    "DMX",
                    "Snow+Patrol",
                    "Dave",
                    "Ha*Ash",
                    "Joyner+Lucas",
                    "Kelly+Rowland",
                    "Keane",
                    "Afrojack",
                    "Incubus",
                    "Gryffin",
                    "Apache+207",
                    "Powfu",
                    "Tee+Grizzley",
                    "Lil+Dicky",
                    "Stray+Kids",
                    "Yo+Gotti",
                    "Los+Tigres+Del+Norte",
                    "Ali+Gatie",
                    "Gigi+D\'\'Agostino",
                    "Aloe+Blacc",
                    "Nekfeu",
                    "Tom+Odell",
                    "Ciara",
                    "Cosculluela",
                    "Santana",
                    "Trevor+Daniel",
                    "KISS",
                    "Rod+Wave",
                    "Quinn+XCII",
                    "TKKG",
                    "Elevation+Worship",
                    "Frédéric+Chopin",
                    "Wale",
                    "MAX",
                    "Sara+Bareilles",
                    "Conor+Maynard",
                    "Jay+Wheeler",
                    "Kacey+Musgraves",
                    "Swedish+House+Mafia",
                    "Zoé",
                    "Thalia",
                    "Ben+Howard",
                    "Old+Dominion",
                    "SEVENTEEN",
                    "Bryant+Myers",
                    "Willy+William",
                    "Lady+A",
                    "Booba",
                    "CHVRCHES",
                    "Martin+Jensen",
                    "Moneybagg+Yo",
                    "Blueface",
                    "Nas",
                    "Wham!",
                    "Mötley+Crüe",
                    "ANAVITÓRIA",
                    "Gente+De+Zona",
                    "La+Oreja+de+Van+Gogh",
                    "Sufjan+Stevens",
                    "Natanael+Cano",
                    "Bethel+Music",
                    "Daya",
                    "Danna+Paola",
                    "Leona+Lewis",
                    "Casper+Magico",
                    "fun.",
                    "TINI",
                    "The+Jackson+5",
                    "Chief+Keef",
                    "Gwen+Stefani",
                    "Lee+Brice",
                    "Jack+Ü",
                    "Sido",
                    "Felipe+Araújo",
                    "Fergie",
                    "Bruno+&+Marrone",
                    "Sting",
                    "Lord+Huron",
                    "Ice+Cube",
                    "Neil+Young",
                    "John+Lennon",
                    "Arcade+Fire",
                    "Kevin+Roldan",
                    "Kollegah",
                    "Taio+Cruz",
                    "Internet+Money",
                    "Charlie+Brown+Jr.",
                    "Alan+Jackson",
                    "Martin+Solveig",
                    "Denzel+Curry",
                    "MKTO",
                    "Tainy",
                    "AJ+Tracey",
                    "Banda+El+Recodo",
                    "The+National",
                    "Darell",
                    "Yellow+Claw",
                    "Nat+King+Cole",
                    "Chayanne",
                    "Guaynaa",
                    "Sean+Kingston",
                    "Roxette",
                    "Plan+B",
                    "Mon+Laferte",
                    "Paul+Simon",
                    "John+Newman",
                    "Saweetie",
                    "Yung+Gravy",
                    "Granular",
                    "Nipsey+Hussle",
                    "Stromae",
                    "Alex+Rose",
                    "José+José",
                    "Chelsea+Cutler",
                    "Beret",
                    "DJ+Luian",
                    "Shania+Twain",
                    "Electric+Light+Orchestra",
                    "DENNIS",
                    "Calle+13",
                    "Lily+Allen",
                    "Marco+Antonio+Solís",
                    "Mambo+Kingz",
                    "Bullet+For+My+Valentine",
                    "Dolly+Parton",
                    "Brad+Paisley",
                    "deadmau5",
                    "Simple+Plan",
                    "Yusuf+/+Cat+Stevens",
                    "Niska",
                    "The+Pussycat+Dolls",
                    "Lionel+Richie",
                    "League+of+Legends",
                    "The+Goo+Goo+Dolls",
                    "Jay+Chou",
                    "Mike+Perry",
                    "David+Bisbal",
                    "*NSYNC",
                    "Sade",
                    "Chencho+Corleone",
                    "Dilsinho",
                    "will.i.am",
                    "Nina+Simone",
                    "Kylie+Minogue",
                    "Mr.+Probz",
                    "Aitana",
                    "Ferrugem",
                    "James+TW",
                    "Bea+Miller",
                    "The+Who",
                    "Dennis+Lloyd",
                    "Willie+Nelson",
                    "Summer+Cem",
                    "Lalo+Ebratt",
                    "Angus+&+Julia+Stone",
                    "Gavin+James",
                    "Bing+Crosby",
                    "Natalia+Lafourcade",
                    "Tech+N9ne",
                    "Oh+Wonder",
                    "Miranda+Lambert",
                    "Brett+Young",
                    "Tracy+Chapman",
                    "Kiiara",
                    "Jack+&+Jack",
                    "Bill+Withers",
                    "Surfaces",
                    "Dido",
                    "Jeezy",
                    "Audioslave",
                    "Grupo+Firme",
                    "Jasmine+Thompson",
                    "Ruth+B.",
                    "Greeicy",
                    "Will+Smith",
                    "Tom+Walker",
                    "Tears+For+Fears",
                    "Cyndi+Lauper",
                    "Olivia+O\'\'Brien",
                    "Ella+Fitzgerald",
                    "Wolfgang+Amadeus+Mozart",
                    "Jon+Pardi",
                    "Jowell+&+Randy",
                    "Tina+Turner",
                    "Lenny+Kravitz",
                    "YUNGBLUD",
                    "Genesis",
                    "Sin+Bandera",
                    "Blur",
                    "Lil+Xan",
                    "KSI",
                    "Brantley+Gilbert",
                    "Lil+Kleine",
                    "ZZ+Top",
                    "Ramin+Djawadi",
                    "Louis+Armstrong",
                    "Snakehips",
                    "Natiruts",
                    "Sofía+Reyes",
                    "Cigarettes+After+Sex",
                    "Selena",
                    "Oliver+Heldens",
                    "Skepta",
                    "NEFFEX",
                    "Rich+Brian",
                    "girl+in+red",
                    "Ezhel",
                    "LUDMILLA",
                    "Dean+Martin",
                    "The+Head+And+The+Heart",
                    "Lupe+Fiasco",
                    "Tinie+Tempah",
                    "Alina+Baraz",
                    "Capo+Plaza",
                    "TLC",
                    "Lil+Jon",
                    "Toby+Keith",
                    "Lauren+Daigle",
                    "Tori+Kelly",
                    "Maggie+Lindemann",
                    "ZHU",
                    "Juicy+J",
                    "Pabllo+Vittar",
                    "Dynoro",
                    "Ghostemane",
                    "Alice+In+Chains",
                    "Chris+Young",
                    "Alvaro+Soler",
                    "Beck",
                    "Gustavo+Cerati",
                    "Salaam+Remi",
                    "Bruno+Martini",
                    "Timbaland",
                    "Tungevaag",
                    "Feid",
                    "Spice+Girls",
                    "Cher",
                    "Kina",
                    "Mary+J.+Blige",
                    "Seether",
                    "Luísa+Sonza",
                    "Kris+Kross+Amsterdam",
                    "Max+Richter",
                    "Andrea+Bocelli",
                    "Leon+Bridges",
                    "Brent+Faiyaz",
                    "Showtek",
                    "Cash+Cash",
                    "Lykke+Li",
                    "Timmy+Trumpet",
                    "Intocable",
                    "The+All-American+Rejects",
                    "BØRNS",
                    "a-ha",
                    "IU",
                    "Vince+Staples",
                    "AWOLNATION",
                    "Deftones",
                    "Camila",
                    "Melim",
                    "Otis+Redding",
                    "A+R+I+Z+O+N+A",
                    "Jacquees",
                    "Petit+Biscuit",
                    "Emeli+Sandé",
                    "Foals",
                    "Simone+&+Simaria",
                    "Jake+Owen",
                    "Wu-Tang+Clan",
                    "Dadju",
                    "Craig+David",
                    "Frenna",
                    "Gustavo+Mioto",
                    "Supertramp",
                    "A+Tribe+Called+Quest",
                    "Counting+Crows",
                    "Pineapple+StormTv",
                    "Grouplove",
                    "Cro",
                    "Baby+Lullaby+Academy",
                    "Pixies",
                    "Beastie+Boys",
                    "Talking+Heads",
                    "KALEO",
                    "Regard",
                    "Gemitaiz",
                    "Ludacris",
                    "Dustin+Lynch",
                    "The+Score",
                    "Foreigner",
                    "Missy+Elliott",
                    "Sam+Cooke",
                    "Death+Cab+for+Cutie",
                    "Dave+Matthews+Band",
                    "Río+Roma",
                    "The+Temptations",
                    "Banda+Los+Recoditos",
                    "Alanis+Morissette",
                    "Kungs",
                    "Stone+Sour",
                    "NCT+127",
                    "Grateful+Dead",
                    "Two+Feet",
                    "La+Adictiva+Banda+San+José+de+Mesillas",
                    "beabadoobee",
                    "Icona+Pop",
                    "Empire+of+the+Sun",
                    "Megadeth",
                    "Los+Temerarios",
                    "Moby",
                    "MadeinTYO",
                    "Famous+Dex",
                    "Tom+Petty+and+the+Heartbreakers",
                    "Ella+Eyre",
                    "ONE+OK+ROCK",
                    "Eurythmics",
                    "LMFAO",
                    "RIN",
                    "Gym+Class+Heroes",
                    "M.I.A.",
                    "Los+Enanitos+Verdes",
                    "Lindsey+Stirling",
                    "SCH",
                    "Disciples",
                    "Gloria+Trevi",
                    "KSHMR",
                    "A+Great+Big+World",
                    "Phoenix",
                    "KC+Rebell",
                    "Roy+Woods",
                    "EDEN",
                    "Juan+Luis+Guerra+4.40",
                    "Ultimo",
                    "Fat+Joe",
                    "Darius+Rucker",
                    "Salmo",
                    "Vintage+Culture",
                    "Bunbury",
                    "Iron+&+Wine",
                    "Jamiroquai",
                    "Digital+Farm+Animals",
                    "MC+Kevin+o+Chris",
                    "BIGBANG",
                    "UB40",
                    "Wallows",
                    "Ricardo+Montaner",
                    "Canserbero",
                    "No+Doubt",
                    "Thiaguinho",
                    "Kaskade",
                    "Duke+Dumont",
                    "Eladio+Carrion",
                    "Alle+Farben",
                    "Brooks+&+Dunn",
                    "The+Kinks",
                    "Falling+In+Reverse",
                    "American+Authors",
                    "AURORA",
                    "Ben&Ben",
                    "Leonard+Cohen",
                    "Micro+TDH",
                    "Pantera",
                    "Chicago",
                    "Matchbox+Twenty",
                    "Smokepurpp",
                    "Kelsea+Ballerini",
                    "Burna+Boy",
                    "Jawsh+685",
                    "Jay+Rock",
                    "Young+the+Giant",
                    "GoldLink",
                    "Slim+Jxmmi",
                    "Deep+Purple",
                    "Chet+Faker",
                    "Ruel",
                    "Brett+Eldredge",
                    "Mc+Livinho"]



## POPULATE THE DATABASE WITH QUERIES ON SPOTIFY API

def populate_database():
    con = psycopg2.connect(database="MelodyDB", user="postgres",password="melody",host="127.0.0.1",port="5432")
    cur = con.cursor()
    popularity = 0
    genres = []
    album_id = 0
    access_token = "[redacted]"
    song_id = 0
    features = []

    ## POPULATE ARTIST TABLE
    for i in range(len(artist_list)):
        search_url_one = "https://api.spotify.com/v1/artists/"
        search_url_two = "https://api.spotify.com/v1/search?query="
        search_url_two_two = "&type=artist&offset=0&limit=1"
        response_query = requests.get(search_url_two + artist_list_two[i] + search_url_two_two + "&" + access_token)
        query_ret = response_query.json()

        artist_id = query_ret.get("artists").get("items")[0].get("id")
        response = requests.get(search_url_one + artist_id + "?" + access_token)
        if response.status_code > 299:
            print("ERROR GETTING ARTISTS ", response.status_code)
            exit(1)
        genres.clear()
        artist_ret = response.json()
        popularity = artist_ret.get("popularity")
        genres = artist_ret.get("genres")

        if len(genres) > 0:
            for g in range(len(genres)):
                genres[g] = genres[g].replace("\'", "\'\'")
            final_str = "INSERT INTO artist (artist_id, name, popularity, genres) VALUES({}, \'{}\', {}, ARRAY{});".format(i+1, artist_list[i], popularity, genres)
            final_str = final_str.replace("\"","\'")
        else:
            final_str = "INSERT INTO artist (artist_id, name, popularity, genres) VALUES({}, \'{}\', {}, null);".format(i+1, artist_list[i], popularity)
        print(final_str)
        cur.execute(final_str)
        time.sleep(0.1)
        con.commit()


        ##POPULATE ALBUM TABLE
        search_url_one = "https://api.spotify.com/v1/artists/"
        search_url_two = "/albums?"
        response = requests.get(search_url_one + artist_id + search_url_two + access_token)
        if response.status_code > 299:
            print("ERROR GETTING ALBUMS ", response.status_code)
            exit(1)
        album_ret = response.json()
        prev_name = album_ret.get("items")[0].get("name")
        prev_two =  prev_name
        num_albums = len(album_ret.get("items"))
        for j in range(15):
            if j >= num_albums:
                continue
            album_name = album_ret.get("items")[j].get("name").replace("\'", "\'\'").replace("\"","\"\"")
            album_release = album_ret.get("items")[j].get("release_date")
            album_length = album_ret.get("items")[j].get("total_tracks")
            s_album_id = album_ret.get("items")[j].get("uri")[14:]
            if album_name != prev_name and album_name != prev_two and album_length > 1:
                album_id += 1
                prev_two =  prev_name

                # If the album's release is not provided as a full date
                if len(album_release) == 4:
                    album_release = album_release + "-01-01"
                elif len(album_release) == 7:
                    album_release = album_release + "-01"

                final_str = "INSERT INTO album (title, album_id, artist_id, release_date, album_length) VALUES(\'{}\',{}, {}, \'{}\', {});".format(album_name, album_id, i+1, album_release, album_length)
                print(final_str)
                time.sleep(0.1)
                cur.execute(final_str)
                prev_name = album_name
                con.commit()

                #POPULATE SONG TABLE
                search_url_one = "https://api.spotify.com/v1/albums/"
                search_url_two = "/tracks?"
                response = requests.get(search_url_one + s_album_id + search_url_two + access_token)
                if response.status_code > 299:
                    print("ERROR GETTING ALBUMS ", response.status_code)
                    exit(1)
                track_ret = response.json()
                track_list = track_ret.get("items")

                for t in range(len(track_list)):
                    track_num = track_list[t].get("track_number")
                    track_name = track_list[t].get("name").replace("\'", "\'\'").replace("\"","\"\"")
                    track_duration = track_list[t].get("duration_ms")
                    song_id += 1

                    for k in range(1, len(track_list[t].get("artists"))):
                        try:
                            indexed_artist = artist_list.index(track_list[t].get("artists")[k].get("name"))
                            features.append(indexed_artist+1)
                        except:
                            pass

                    if len(features) > 0:
                        final_str = "INSERT INTO song (title, rewards, song_id, artist_id, album_id, artist_features, track_num, duration_ms) VALUES(\'{}\', null,{}, {}, {}, ARRAY{}, {}, {});".format(track_name, song_id, i+1, album_id, features, track_num, track_duration)
                        print(final_str)
                        cur.execute(final_str)
                    else:
                        final_str = "INSERT INTO song (title, rewards, song_id, artist_id, album_id, artist_features, track_num, duration_ms) VALUES(\'{}\', null,{}, {}, {}, null, {}, {});".format(track_name, song_id, i+1, album_id, track_num, track_duration)
                        print(final_str)
                        cur.execute(final_str)
                    features.clear()
                con.commit()
    con.close()

populate_database()

